spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fatSecret
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
base_url: http://www.fatsecret.ru